import type { Repository } from "./types";

export const repositories: Repository[] = [
  {
    name: "AgentFoundry-instantly",
    description: "AI development workspace and Electron desktop tooling.",
    language: "JavaScript",
    kind: "active",
    health: "healthy",
    openPulls: 0,
    lastActivity: "12 Jul 2026",
    checks: "Node 22 CI passing",
    recommendation: "Keep active",
  },
  {
    name: "azeroth-pilot-reloaded-Pro-",
    description: "QuestMaster Pro WoW guide addon.",
    language: "Lua",
    kind: "active",
    health: "healthy",
    openPulls: 0,
    lastActivity: "11 Jul 2026",
    checks: "Lua 5.1 + TOC checks passing",
    recommendation: "Keep active",
  },
  {
    name: "Test-New-",
    description: "Prisma React/Vite Gemini application with meaningful history.",
    language: "TypeScript",
    kind: "experiment",
    health: "attention",
    openPulls: 0,
    lastActivity: "22 Jan 2026",
    checks: "No persistent CI detected",
    recommendation: "Rename to prisma-ai-studio",
  },
  {
    name: "nEW-tEST",
    description: "Auto-generated Emergent test workspace.",
    language: "Mixed",
    kind: "cleanup",
    health: "review",
    openPulls: 0,
    lastActivity: "4 Feb 2026",
    checks: "Generated commits only",
    recommendation: "Archive after final review",
  },
  {
    name: "NebulaUltimate",
    description: "Canonical Python/Ollama offline development platform.",
    language: "Python",
    kind: "active",
    health: "attention",
    openPulls: 0,
    lastActivity: "13 Jul 2026",
    checks: "Legacy material preserved",
    recommendation: "Add build and lint CI",
  },
  {
    name: "TrinityCore",
    description: "Large inherited upstream codebase.",
    language: "C++",
    kind: "upstream",
    health: "review",
    openPulls: 0,
    lastActivity: "Upstream tracked",
    checks: "Owner changes not detected",
    recommendation: "Document sync policy",
  },
];
